### ISSUE TITLE
Getting an error while running GUI on Windows 10

### ISSUE THREAD

**Issue by Dreamz-Dziner** [jhj0517/sam2-playground#31]
Hi, I have installed the repo with all the necessary requirements but when whenever I try to upload the  video in the gui it always generates an error. Can you please help me solve this issue. Thank you so much.

![Error](https://github.com/user-attachments/assets/6f465857-169f-4995-8ce4-330061a78d2d)

**Comment by jhj0517** [comment]
Hi @Dreamz-Dziner, Thanks for reporting. I just reproduced the same thing and it's fixed in #32.

If you run
```
pip insatll -U -r requirements.txt
```
again with the latest commit, it should work fine.

If you still have a problem, please let me know!

**Comment by Dreamz-Dziner** [comment]
Hey. Thank you so much for posting a solution fast. Totally appreciate your efforts for giving such an awesome gui.
