### ISSUE TITLE
How to flip mask for solid color? 

### ISSUE THREAD

**Issue by Askejm** [jhj0517/sam2-playground#4]
I would like to use this tool for quick green screens. I see there already is the solid color option, however this is only the object itself and not the background.

**Comment by jhj0517** [comment]
Hi. You want the object to have a green background, right? 
Adding "Invert mask" option is a good idea. I'll work on that.

**Comment by jhj0517** [comment]
@Askejm 
I've added "invert mask" option,

![image](https://github.com/user-attachments/assets/3c22ee73-cbb3-43b5-9449-1e1263d2fef6)

it works fine on my test, can you check the latest version?

https://github.com/user-attachments/assets/1ff11c57-04a7-4dbb-b1cd-422beb89839c

**Comment by Askejm** [comment]
@jhj0517  Works great. Thank you so much! This is very useful, I use it for my video editing. While I'm at it, you could also consider borrowing some functionality [from this tool, based on SAM1](https://github.com/gaomingqi/Track-Anything). I've used it a lot and the multi mask feature and inpainting is super useful. I'm hoping a tool of similar functionality can make it, but with SAM2!
